# Generated by Django 5.1 on 2024-08-14 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='candidate',
        ),
    ]
